# These are supported funding model platforms

github: [rutvij26]
# ko_fi: # Replace with your Ko-fi username
# open_collective: # Replace with your Open Collective username
# patreon: # Replace with your Patreon username
# tidelift: # Replace with your Tidelift username
# community_bridge: # Replace with your Community Bridge project-id
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
# custom: # Replace with your custom funding URL
